/* Generated by Yosys 0.38+92 (git sha1 84116c9a3, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1708682804602/work=/usr/local/src/conda/yosys-0.38_93_g84116c9a3 -fdebug-prefix-map=/home/felipe-zorro/miniconda3/envs/digital=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

/* hdlname = "mult" */
/* top =  1  */
/* src = "mult.v:1.1-34.10" */
module mult(clk, rst, init, A, B, R, done);
  /* src = "mult.v:5.13-5.14" */
  input [15:0] A;
  wire [15:0] A;
  wire [15:1] A_LUT4_B_Z;
  /* src = "mult.v:6.13-6.14" */
  input [15:0] B;
  wire [15:0] B;
  wire [14:0] B_LUT4_B_Z;
  /* src = "mult.v:8.14-8.15" */
  output [31:0] R;
  wire [31:0] R;
  /* hdlname = "acc0 A" */
  /* src = "acc.v:5.13-5.14" */
  wire [15:0] \acc0.A ;
  /* hdlname = "acc0 R" */
  /* src = "acc.v:6.17-6.18" */
  wire [31:0] \acc0.R ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.R_CCU2C_B0_1_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.R_CCU2C_B0_2_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.R_CCU2C_B0_3_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.R_CCU2C_B0_4_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.R_CCU2C_B0_5_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.R_CCU2C_B0_6_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.R_CCU2C_B0_7_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  /* unused_bits = "0" */
  wire \acc0.R_CCU2C_B0_COUT ;
  /* force_downto = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:34.26-34.27" */
  wire [31:0] \acc0.R_TRELLIS_FF_Q_DI ;
  /* hdlname = "acc0 acc" */
  /* src = "acc.v:3.7-3.10" */
  wire \acc0.acc ;
  wire \acc0.acc_TRELLIS_FF_Q_DI ;
  /* hdlname = "acc0 clk" */
  /* src = "acc.v:2.7-2.10" */
  wire \acc0.clk ;
  /* src = "mult.v:2.7-2.10" */
  input clk;
  wire clk;
  /* hdlname = "comp0 B" */
  /* src = "comp.v:2.13-2.14" */
  wire [15:0] \comp0.B ;
  /* src = "mult.v:9.8-9.12" */
  output done;
  wire done;
  /* src = "mult.v:4.7-4.11" */
  input init;
  wire init;
  /* force_downto = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [1:0] init_LUT4_A_1_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [3:0] init_LUT4_A_D;
  /* force_downto = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [4:0] init_LUT4_A_D_LUT4_Z_C;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.34-141.36" */
  wire init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D0;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.22-141.24" */
  wire init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D0_PFUMX_Z_ALUT;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.18-141.20" */
  wire init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D0_PFUMX_Z_BLUT;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.38-141.40" */
  wire init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D1;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.30-141.32" */
  wire init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D1_PFUMX_Z_ALUT;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.26-141.28" */
  wire init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D1_PFUMX_Z_BLUT;
  wire [5:0] init_LUT4_A_Z;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire init_LUT4_A_Z_PFUMX_Z_1_ALUT;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire init_LUT4_A_Z_PFUMX_Z_1_BLUT;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire init_LUT4_A_Z_PFUMX_Z_ALUT;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire init_LUT4_A_Z_PFUMX_Z_BLUT;
  /* force_downto = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [4:0] init_LUT4_C_Z;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire init_LUT4_C_Z_PFUMX_Z_1_ALUT;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire init_LUT4_C_Z_PFUMX_Z_1_BLUT;
  /* force_downto = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [4:0] init_LUT4_C_Z_PFUMX_Z_1_C0;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire init_LUT4_C_Z_PFUMX_Z_BLUT;
  /* force_downto = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [4:0] init_LUT4_C_Z_PFUMX_Z_C0;
  /* hdlname = "regA0 A" */
  /* src = "regA.v:5.13-5.14" */
  wire [15:0] \regA0.A ;
  /* hdlname = "regA0 Aout" */
  /* src = "regA.v:6.17-6.21" */
  wire [15:0] \regA0.Aout ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \regA0.Aout_CCU2C_A0_1_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \regA0.Aout_CCU2C_A0_2_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \regA0.Aout_CCU2C_A0_3_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \regA0.Aout_CCU2C_A0_4_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \regA0.Aout_CCU2C_A0_5_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \regA0.Aout_CCU2C_A0_6_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \regA0.Aout_CCU2C_A0_7_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \regA0.Aout_CCU2C_A0_COUT ;
  /* hdlname = "regA0 clk" */
  /* src = "regA.v:2.7-2.10" */
  wire \regA0.clk ;
  /* hdlname = "regA0 shift" */
  /* src = "regA.v:4.7-4.12" */
  wire \regA0.shift ;
  wire \regA0.shift_LUT4_C_Z ;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \regA0.shift_LUT4_D_Z ;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \regA0.shift_LUT4_D_Z_PFUMX_BLUT_ALUT ;
  /* force_downto = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [2:0] \regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z ;
  /* hdlname = "regB0 B" */
  /* src = "regB.v:5.13-5.14" */
  wire [15:0] \regB0.B ;
  /* hdlname = "regB0 Bout" */
  /* src = "regB.v:6.17-6.21" */
  wire [15:0] \regB0.Bout ;
  /* hdlname = "regB0 clk" */
  /* src = "regB.v:2.7-2.10" */
  wire \regB0.clk ;
  /* hdlname = "regB0 shift" */
  /* src = "regB.v:4.7-4.12" */
  wire \regB0.shift ;
  /* src = "mult.v:3.7-3.10" */
  input rst;
  wire rst;
  /* hdlname = "state_machinemult0 acc" */
  /* src = "state_machinemult.v:8.12-8.15" */
  wire \state_machinemult0.acc ;
  /* hdlname = "state_machinemult0 b0" */
  /* src = "state_machinemult.v:6.7-6.9" */
  wire \state_machinemult0.b0 ;
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \state_machinemult0.b0_LUT4_D_1_Z ;
  /* hdlname = "state_machinemult0 clk" */
  /* src = "state_machinemult.v:2.7-2.10" */
  wire \state_machinemult0.clk ;
  /* hdlname = "state_machinemult0 counter" */
  /* src = "state_machinemult.v:30.11-30.18" */
  wire [4:0] \state_machinemult0.counter ;
  /* abc9_carry = 32'd1 */
  /* src = "state_machinemult.v:70.28-70.39|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \state_machinemult0.counter_CCU2C_B0_1_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "state_machinemult.v:70.28-70.39|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \state_machinemult0.counter_CCU2C_B0_2_COUT ;
  /* unused_bits = "0" */
  wire \state_machinemult0.counter_CCU2C_B0_2_S0 ;
  /* abc9_carry = 32'd1 */
  /* src = "state_machinemult.v:70.28-70.39|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  /* unused_bits = "0" */
  wire \state_machinemult0.counter_CCU2C_B0_COUT ;
  /* unused_bits = "0" */
  wire \state_machinemult0.counter_CCU2C_B0_S1 ;
  /* force_downto = 32'd1 */
  /* src = "state_machinemult.v:70.28-70.39|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:34.26-34.27" */
  wire [4:0] \state_machinemult0.counter_TRELLIS_FF_Q_DI ;
  wire \state_machinemult0.counter_TRELLIS_FF_Q_LSR ;
  /* hdlname = "state_machinemult0 done" */
  /* src = "state_machinemult.v:11.12-11.16" */
  wire \state_machinemult0.done ;
  /* hdlname = "state_machinemult0 init" */
  /* src = "state_machinemult.v:4.7-4.11" */
  wire \state_machinemult0.init ;
  /* hdlname = "state_machinemult0 rst" */
  /* src = "state_machinemult.v:3.7-3.10" */
  wire \state_machinemult0.rst ;
  /* hdlname = "state_machinemult0 sh" */
  /* src = "state_machinemult.v:10.12-10.14" */
  wire \state_machinemult0.sh ;
  /* onehot = 32'd1 */
  wire [5:0] \state_machinemult0.state ;
  wire \state_machinemult0.state_TRELLIS_FF_Q_1_DI ;
  /* src = "mult.v:18.12-18.15" */
  wire [15:0] w_a;
  /* src = "mult.v:15.6-15.11" */
  wire w_acc;
  /* src = "mult.v:19.12-19.15" */
  wire [15:0] w_b;
  /* src = "mult.v:14.6-14.10" */
  wire w_sh;
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B (
    .A(1'h0),
    .B(A[10]),
    .C(\regA0.Aout [9]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_1 (
    .A(1'h0),
    .B(A[9]),
    .C(\regA0.Aout [8]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_10 (
    .A(1'h0),
    .B(A[14]),
    .C(\regA0.Aout [13]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_11 (
    .A(1'h0),
    .B(A[13]),
    .C(\regA0.Aout [12]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_12 (
    .A(1'h0),
    .B(A[12]),
    .C(\regA0.Aout [11]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_13 (
    .A(1'h0),
    .B(A[11]),
    .C(\regA0.Aout [10]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_14 (
    .A(1'h0),
    .B(A[1]),
    .C(\regA0.Aout [0]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_2 (
    .A(1'h0),
    .B(A[8]),
    .C(\regA0.Aout [7]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_3 (
    .A(1'h0),
    .B(A[7]),
    .C(\regA0.Aout [6]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_4 (
    .A(1'h0),
    .B(A[6]),
    .C(\regA0.Aout [5]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_5 (
    .A(1'h0),
    .B(A[5]),
    .C(\regA0.Aout [4]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_6 (
    .A(1'h0),
    .B(A[4]),
    .C(\regA0.Aout [3]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_7 (
    .A(1'h0),
    .B(A[3]),
    .C(\regA0.Aout [2]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_8 (
    .A(1'h0),
    .B(A[2]),
    .C(\regA0.Aout [1]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_9 (
    .A(1'h0),
    .B(A[15]),
    .C(\regA0.Aout [14]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(A_LUT4_B_Z[15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B (
    .A(1'h0),
    .B(B[9]),
    .C(\regB0.Bout [10]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_1 (
    .A(1'h0),
    .B(B[8]),
    .C(\regB0.Bout [9]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_10 (
    .A(1'h0),
    .B(B[13]),
    .C(\regB0.Bout [14]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_11 (
    .A(1'h0),
    .B(B[12]),
    .C(\regB0.Bout [13]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_12 (
    .A(1'h0),
    .B(B[11]),
    .C(\regB0.Bout [12]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_13 (
    .A(1'h0),
    .B(B[10]),
    .C(\regB0.Bout [11]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_14 (
    .A(1'h0),
    .B(B[0]),
    .C(\regB0.Bout [1]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_2 (
    .A(1'h0),
    .B(B[7]),
    .C(\regB0.Bout [8]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_3 (
    .A(1'h0),
    .B(B[6]),
    .C(\regB0.Bout [7]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_4 (
    .A(1'h0),
    .B(B[5]),
    .C(\regB0.Bout [6]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_5 (
    .A(1'h0),
    .B(B[4]),
    .C(\regB0.Bout [5]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_6 (
    .A(1'h0),
    .B(B[3]),
    .C(\regB0.Bout [4]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_7 (
    .A(1'h0),
    .B(B[2]),
    .C(\regB0.Bout [3]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_8 (
    .A(1'h0),
    .B(B[1]),
    .C(\regB0.Bout [2]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_9 (
    .A(1'h0),
    .B(B[14]),
    .C(\regB0.Bout [15]),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(B_LUT4_B_Z[14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.R_CCU2C_B0  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\acc0.R [30]),
    .B1(\acc0.R [31]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.R_CCU2C_B0_1_COUT ),
    .COUT(\acc0.R_CCU2C_B0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [30]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.R_CCU2C_B0_1  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\acc0.R [28]),
    .B1(\acc0.R [29]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.R_CCU2C_B0_2_COUT ),
    .COUT(\acc0.R_CCU2C_B0_1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [28]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.R_CCU2C_B0_2  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\acc0.R [26]),
    .B1(\acc0.R [27]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.R_CCU2C_B0_3_COUT ),
    .COUT(\acc0.R_CCU2C_B0_2_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [26]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.R_CCU2C_B0_3  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\acc0.R [24]),
    .B1(\acc0.R [25]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.R_CCU2C_B0_4_COUT ),
    .COUT(\acc0.R_CCU2C_B0_3_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [24]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.R_CCU2C_B0_4  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\acc0.R [22]),
    .B1(\acc0.R [23]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.R_CCU2C_B0_5_COUT ),
    .COUT(\acc0.R_CCU2C_B0_4_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [22]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.R_CCU2C_B0_5  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\acc0.R [20]),
    .B1(\acc0.R [21]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.R_CCU2C_B0_6_COUT ),
    .COUT(\acc0.R_CCU2C_B0_5_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [20]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.R_CCU2C_B0_6  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\acc0.R [18]),
    .B1(\acc0.R [19]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.R_CCU2C_B0_7_COUT ),
    .COUT(\acc0.R_CCU2C_B0_6_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [18]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.R_CCU2C_B0_7  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\acc0.R [16]),
    .B1(\acc0.R [17]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\regA0.Aout_CCU2C_A0_4_COUT ),
    .COUT(\acc0.R_CCU2C_B0_7_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [16]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [31]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_1  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [30]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [30])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_10  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [21]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_11  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [20]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_12  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [19]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_13  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [18]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_14  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [17]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_15  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [16]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_16  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [15]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_17  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [14]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_18  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [13]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_19  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [12]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_2  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [29]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_20  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [11]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_21  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [10]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_22  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [9]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_23  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [8]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_24  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [7]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_25  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [6]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_26  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [5]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_27  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [4]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_28  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [3]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_29  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [2]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_3  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [28]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [28])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_30  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [1]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_31  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [0]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_4  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [27]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_5  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [26]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [26])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_6  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [25]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_7  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [24]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [24])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_8  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [23]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:11.1-15.8|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.R_TRELLIS_FF_Q_9  (
    .CE(\acc0.acc ),
    .CLK(clk),
    .DI(\acc0.R_TRELLIS_FF_Q_DI [22]),
    .LSR(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Q(\acc0.R [22])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc0.acc_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\acc0.acc_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\acc0.acc )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) done_TRELLIS_FF_Q (
    .CLK(clk),
    .DI(init_LUT4_A_Z[4]),
    .LSR(1'h0),
    .Q(done)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hffdc)
  ) init_LUT4_A (
    .A(init),
    .B(rst),
    .C(\state_machinemult0.state [0]),
    .D(init_LUT4_A_D[3]),
    .Z(init_LUT4_A_Z[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h2230)
  ) init_LUT4_A_1 (
    .A(init),
    .B(rst),
    .C(done),
    .D(\state_machinemult0.state [0]),
    .Z(init_LUT4_A_1_Z[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) init_LUT4_A_1_Z_LUT4_D (
    .A(1'h0),
    .B(1'h0),
    .C(done),
    .D(init_LUT4_A_1_Z[1]),
    .Z(\state_machinemult0.counter_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) init_LUT4_A_D_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(init_LUT4_A_D_LUT4_Z_C[3]),
    .D(done),
    .Z(init_LUT4_A_D[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:154.21-154.62" */
  L6MUX21 init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z (
    .D0(init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D0),
    .D1(init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D1),
    .SD(\state_machinemult0.counter [0]),
    .Z(init_LUT4_A_D_LUT4_Z_C[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:152.19-152.65" */
  PFUMX init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D0_PFUMX_Z (
    .ALUT(init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D0_PFUMX_Z_ALUT),
    .BLUT(init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D0_PFUMX_Z_BLUT),
    .C0(\state_machinemult0.counter [1]),
    .Z(init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D0)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:144.39-145.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(done),
    .Z(init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D0_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:142.39-143.56" */
  LUT4 #(
    .INIT(16'h4ccc)
  ) init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z (
    .A(\state_machinemult0.counter [4]),
    .B(done),
    .C(\state_machinemult0.counter [3]),
    .D(\state_machinemult0.counter [2]),
    .Z(init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D0_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:153.19-153.65" */
  PFUMX init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D1_PFUMX_Z (
    .ALUT(init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D1_PFUMX_Z_ALUT),
    .BLUT(init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D1_PFUMX_Z_BLUT),
    .C0(\state_machinemult0.counter [1]),
    .Z(init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:149.39-150.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(done),
    .Z(init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D1_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:147.39-148.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(done),
    .Z(init_LUT4_A_D_LUT4_Z_C_L6MUX21_Z_D1_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX init_LUT4_A_Z_PFUMX_Z (
    .ALUT(init_LUT4_A_Z_PFUMX_Z_ALUT),
    .BLUT(init_LUT4_A_Z_PFUMX_Z_BLUT),
    .C0(init_LUT4_C_Z[0]),
    .Z(init_LUT4_A_Z[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX init_LUT4_A_Z_PFUMX_Z_1 (
    .ALUT(init_LUT4_A_Z_PFUMX_Z_1_ALUT),
    .BLUT(init_LUT4_A_Z_PFUMX_Z_1_BLUT),
    .C0(init_LUT4_C_Z[4]),
    .Z(init_LUT4_A_Z[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h3310)
  ) init_LUT4_A_Z_PFUMX_Z_1_ALUT_LUT4_Z (
    .A(init_LUT4_C_Z[0]),
    .B(rst),
    .C(\state_machinemult0.state [1]),
    .D(init_LUT4_C_Z[3]),
    .Z(init_LUT4_A_Z_PFUMX_Z_1_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h3330)
  ) init_LUT4_A_Z_PFUMX_Z_1_BLUT_LUT4_Z (
    .A(1'h0),
    .B(rst),
    .C(\state_machinemult0.state [1]),
    .D(init_LUT4_C_Z[3]),
    .Z(init_LUT4_A_Z_PFUMX_Z_1_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h3320)
  ) init_LUT4_A_Z_PFUMX_Z_ALUT_LUT4_Z (
    .A(init_LUT4_C_Z[4]),
    .B(rst),
    .C(\state_machinemult0.state [1]),
    .D(init_LUT4_A_D_LUT4_Z_C[3]),
    .Z(init_LUT4_A_Z_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) init_LUT4_A_Z_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(rst),
    .D(init_LUT4_A_D_LUT4_Z_C[3]),
    .Z(init_LUT4_A_Z_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hf000)
  ) init_LUT4_C (
    .A(1'h0),
    .B(1'h0),
    .C(init),
    .D(\state_machinemult0.state [0]),
    .Z(init_LUT4_C_Z[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX init_LUT4_C_Z_PFUMX_Z (
    .ALUT(\state_machinemult0.b0_LUT4_D_1_Z ),
    .BLUT(init_LUT4_C_Z_PFUMX_Z_BLUT),
    .C0(init_LUT4_C_Z_PFUMX_Z_C0[4]),
    .Z(init_LUT4_C_Z[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX init_LUT4_C_Z_PFUMX_Z_1 (
    .ALUT(init_LUT4_C_Z_PFUMX_Z_1_ALUT),
    .BLUT(init_LUT4_C_Z_PFUMX_Z_1_BLUT),
    .C0(init_LUT4_C_Z_PFUMX_Z_1_C0[4]),
    .Z(init_LUT4_C_Z[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) init_LUT4_C_Z_PFUMX_Z_1_ALUT_LUT4_Z (
    .A(\regB0.Bout [7]),
    .B(\regB0.Bout [6]),
    .C(\regB0.Bout [5]),
    .D(\regB0.Bout [4]),
    .Z(init_LUT4_C_Z_PFUMX_Z_1_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) init_LUT4_C_Z_PFUMX_Z_1_BLUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(init_LUT4_C_Z_PFUMX_Z_1_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) init_LUT4_C_Z_PFUMX_Z_1_C0_LUT4_Z (
    .A(\regB0.Bout [11]),
    .B(\regB0.Bout [10]),
    .C(\regB0.Bout [9]),
    .D(\regB0.Bout [8]),
    .Z(init_LUT4_C_Z_PFUMX_Z_1_C0[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) init_LUT4_C_Z_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(init_LUT4_C_Z_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) init_LUT4_C_Z_PFUMX_Z_C0_LUT4_Z (
    .A(\regB0.Bout [15]),
    .B(\regB0.Bout [14]),
    .C(\regB0.Bout [13]),
    .D(\regB0.Bout [12]),
    .Z(init_LUT4_C_Z_PFUMX_Z_C0[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \regA0.Aout_CCU2C_A0  (
    .A0(\regA0.Aout [8]),
    .A1(\regA0.Aout [9]),
    .B0(\acc0.R [8]),
    .B1(\acc0.R [9]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\regA0.Aout_CCU2C_A0_1_COUT ),
    .COUT(\regA0.Aout_CCU2C_A0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [8]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \regA0.Aout_CCU2C_A0_1  (
    .A0(\regA0.Aout [6]),
    .A1(\regA0.Aout [7]),
    .B0(\acc0.R [6]),
    .B1(\acc0.R [7]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\regA0.Aout_CCU2C_A0_2_COUT ),
    .COUT(\regA0.Aout_CCU2C_A0_1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [6]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \regA0.Aout_CCU2C_A0_2  (
    .A0(\regA0.Aout [4]),
    .A1(\regA0.Aout [5]),
    .B0(\acc0.R [4]),
    .B1(\acc0.R [5]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\regA0.Aout_CCU2C_A0_3_COUT ),
    .COUT(\regA0.Aout_CCU2C_A0_2_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [4]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \regA0.Aout_CCU2C_A0_3  (
    .A0(\regA0.Aout [2]),
    .A1(\regA0.Aout [3]),
    .B0(\acc0.R [2]),
    .B1(\acc0.R [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\regA0.Aout_CCU2C_A0_7_COUT ),
    .COUT(\regA0.Aout_CCU2C_A0_3_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [2]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \regA0.Aout_CCU2C_A0_4  (
    .A0(\regA0.Aout [14]),
    .A1(\regA0.Aout [15]),
    .B0(\acc0.R [14]),
    .B1(\acc0.R [15]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\regA0.Aout_CCU2C_A0_5_COUT ),
    .COUT(\regA0.Aout_CCU2C_A0_4_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [14]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \regA0.Aout_CCU2C_A0_5  (
    .A0(\regA0.Aout [12]),
    .A1(\regA0.Aout [13]),
    .B0(\acc0.R [12]),
    .B1(\acc0.R [13]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\regA0.Aout_CCU2C_A0_6_COUT ),
    .COUT(\regA0.Aout_CCU2C_A0_5_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [12]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \regA0.Aout_CCU2C_A0_6  (
    .A0(\regA0.Aout [10]),
    .A1(\regA0.Aout [11]),
    .B0(\acc0.R [10]),
    .B1(\acc0.R [11]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\regA0.Aout_CCU2C_A0_COUT ),
    .COUT(\regA0.Aout_CCU2C_A0_6_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [10]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:14.28-14.41|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \regA0.Aout_CCU2C_A0_7  (
    .A0(\regA0.Aout [0]),
    .A1(\regA0.Aout [1]),
    .B0(\acc0.R [0]),
    .B1(\acc0.R [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\regA0.Aout_CCU2C_A0_7_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.R_TRELLIS_FF_Q_DI [0]),
    .S1(\acc0.R_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \regA0.Aout_TRELLIS_FF_Q  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A[0]),
    .LSR(\regA0.shift ),
    .Q(\regA0.Aout [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_1  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[15]),
    .LSR(1'h0),
    .Q(\regA0.Aout [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_10  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[6]),
    .LSR(1'h0),
    .Q(\regA0.Aout [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_11  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[5]),
    .LSR(1'h0),
    .Q(\regA0.Aout [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_12  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[4]),
    .LSR(1'h0),
    .Q(\regA0.Aout [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_13  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[3]),
    .LSR(1'h0),
    .Q(\regA0.Aout [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_14  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[2]),
    .LSR(1'h0),
    .Q(\regA0.Aout [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_15  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[1]),
    .LSR(1'h0),
    .Q(\regA0.Aout [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_2  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[14]),
    .LSR(1'h0),
    .Q(\regA0.Aout [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_3  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[13]),
    .LSR(1'h0),
    .Q(\regA0.Aout [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_4  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[12]),
    .LSR(1'h0),
    .Q(\regA0.Aout [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_5  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[11]),
    .LSR(1'h0),
    .Q(\regA0.Aout [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_6  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[10]),
    .LSR(1'h0),
    .Q(\regA0.Aout [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_7  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[9]),
    .LSR(1'h0),
    .Q(\regA0.Aout [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_8  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[8]),
    .LSR(1'h0),
    .Q(\regA0.Aout [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regA.v:8.1-14.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.Aout_TRELLIS_FF_Q_9  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[7]),
    .LSR(1'h0),
    .Q(\regA0.Aout [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) \regA0.shift_LUT4_C  (
    .A(1'h0),
    .B(1'h0),
    .C(\regA0.shift ),
    .D(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2]),
    .Z(\regA0.shift_LUT4_C_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \regA0.shift_LUT4_D  (
    .A(done),
    .B(\state_machinemult0.state [3]),
    .C(\state_machinemult0.state [1]),
    .D(\regA0.shift ),
    .Z(\regA0.shift_LUT4_D_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \regA0.shift_LUT4_D_Z_PFUMX_BLUT  (
    .ALUT(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_ALUT ),
    .BLUT(\regA0.shift_LUT4_D_Z ),
    .C0(\acc0.acc ),
    .Z(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \regA0.shift_LUT4_D_Z_PFUMX_BLUT_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\regA0.shift_LUT4_D_Z_PFUMX_BLUT_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regA0.shift_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(init_LUT4_A_Z[5]),
    .LSR(1'h0),
    .Q(\regA0.shift )
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regB0.Bout_TRELLIS_FF_Q  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[14]),
    .LSR(1'h0),
    .Q(\regB0.Bout [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regB0.Bout_TRELLIS_FF_Q_1  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[13]),
    .LSR(1'h0),
    .Q(\regB0.Bout [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regB0.Bout_TRELLIS_FF_Q_10  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[4]),
    .LSR(1'h0),
    .Q(\regB0.Bout [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regB0.Bout_TRELLIS_FF_Q_11  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[3]),
    .LSR(1'h0),
    .Q(\regB0.Bout [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regB0.Bout_TRELLIS_FF_Q_12  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[2]),
    .LSR(1'h0),
    .Q(\regB0.Bout [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regB0.Bout_TRELLIS_FF_Q_13  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[1]),
    .LSR(1'h0),
    .Q(\regB0.Bout [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \regB0.Bout_TRELLIS_FF_Q_14  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B[15]),
    .LSR(\regA0.shift ),
    .Q(\regB0.Bout [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regB0.Bout_TRELLIS_FF_Q_2  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[12]),
    .LSR(1'h0),
    .Q(\regB0.Bout [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regB0.Bout_TRELLIS_FF_Q_3  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[11]),
    .LSR(1'h0),
    .Q(\regB0.Bout [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regB0.Bout_TRELLIS_FF_Q_4  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[10]),
    .LSR(1'h0),
    .Q(\regB0.Bout [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regB0.Bout_TRELLIS_FF_Q_5  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[9]),
    .LSR(1'h0),
    .Q(\regB0.Bout [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regB0.Bout_TRELLIS_FF_Q_6  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[8]),
    .LSR(1'h0),
    .Q(\regB0.Bout [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regB0.Bout_TRELLIS_FF_Q_7  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[7]),
    .LSR(1'h0),
    .Q(\regB0.Bout [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regB0.Bout_TRELLIS_FF_Q_8  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[6]),
    .LSR(1'h0),
    .Q(\regB0.Bout [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \regB0.Bout_TRELLIS_FF_Q_9  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[5]),
    .LSR(1'h0),
    .Q(\regB0.Bout [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h5504)
  ) \state_machinemult0.b0_LUT4_C  (
    .A(rst),
    .B(\state_machinemult0.state [3]),
    .C(\state_machinemult0.b0 ),
    .D(\acc0.acc ),
    .Z(init_LUT4_A_Z[5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3000)
  ) \state_machinemult0.b0_LUT4_D  (
    .A(1'h0),
    .B(rst),
    .C(\state_machinemult0.state [3]),
    .D(\state_machinemult0.b0 ),
    .Z(\acc0.acc_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \state_machinemult0.b0_LUT4_D_1  (
    .A(\regB0.Bout [3]),
    .B(\regB0.Bout [2]),
    .C(\regB0.Bout [1]),
    .D(\state_machinemult0.b0 ),
    .Z(\state_machinemult0.b0_LUT4_D_1_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "regB.v:8.1-13.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \state_machinemult0.b0_TRELLIS_FF_Q  (
    .CE(\regA0.shift_LUT4_C_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[0]),
    .LSR(1'h0),
    .Q(\state_machinemult0.b0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "state_machinemult.v:70.28-70.39|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \state_machinemult0.counter_CCU2C_B0  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\state_machinemult0.counter [4]),
    .B1(1'h0),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\state_machinemult0.counter_CCU2C_B0_1_COUT ),
    .COUT(\state_machinemult0.counter_CCU2C_B0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\state_machinemult0.counter_TRELLIS_FF_Q_DI [4]),
    .S1(\state_machinemult0.counter_CCU2C_B0_S1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "state_machinemult.v:70.28-70.39|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \state_machinemult0.counter_CCU2C_B0_1  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\state_machinemult0.counter [2]),
    .B1(\state_machinemult0.counter [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\state_machinemult0.counter_CCU2C_B0_2_COUT ),
    .COUT(\state_machinemult0.counter_CCU2C_B0_1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\state_machinemult0.counter_TRELLIS_FF_Q_DI [2]),
    .S1(\state_machinemult0.counter_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "state_machinemult.v:70.28-70.39|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \state_machinemult0.counter_CCU2C_B0_2  (
    .A0(1'h1),
    .A1(1'h0),
    .B0(\state_machinemult0.counter [0]),
    .B1(\state_machinemult0.counter [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\state_machinemult0.counter_CCU2C_B0_2_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\state_machinemult0.counter_CCU2C_B0_2_S0 ),
    .S1(\state_machinemult0.counter_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \state_machinemult0.counter_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\state_machinemult0.counter [0]),
    .Z(\state_machinemult0.counter_TRELLIS_FF_Q_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "state_machinemult.v:32.1-81.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \state_machinemult0.counter_TRELLIS_FF_Q  (
    .CE(init_LUT4_A_1_Z[1]),
    .CLK(clk),
    .DI(\state_machinemult0.counter_TRELLIS_FF_Q_DI [4]),
    .LSR(\state_machinemult0.counter_TRELLIS_FF_Q_LSR ),
    .Q(\state_machinemult0.counter [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "state_machinemult.v:32.1-81.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \state_machinemult0.counter_TRELLIS_FF_Q_1  (
    .CE(init_LUT4_A_1_Z[1]),
    .CLK(clk),
    .DI(\state_machinemult0.counter_TRELLIS_FF_Q_DI [3]),
    .LSR(\state_machinemult0.counter_TRELLIS_FF_Q_LSR ),
    .Q(\state_machinemult0.counter [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "state_machinemult.v:32.1-81.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \state_machinemult0.counter_TRELLIS_FF_Q_2  (
    .CE(init_LUT4_A_1_Z[1]),
    .CLK(clk),
    .DI(\state_machinemult0.counter_TRELLIS_FF_Q_DI [2]),
    .LSR(\state_machinemult0.counter_TRELLIS_FF_Q_LSR ),
    .Q(\state_machinemult0.counter [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "state_machinemult.v:32.1-81.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \state_machinemult0.counter_TRELLIS_FF_Q_3  (
    .CE(init_LUT4_A_1_Z[1]),
    .CLK(clk),
    .DI(\state_machinemult0.counter_TRELLIS_FF_Q_DI [1]),
    .LSR(\state_machinemult0.counter_TRELLIS_FF_Q_LSR ),
    .Q(\state_machinemult0.counter [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "state_machinemult.v:32.1-81.4|/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \state_machinemult0.counter_TRELLIS_FF_Q_4  (
    .CE(init_LUT4_A_1_Z[1]),
    .CLK(clk),
    .DI(\state_machinemult0.counter_TRELLIS_FF_Q_DI [0]),
    .LSR(\state_machinemult0.counter_TRELLIS_FF_Q_LSR ),
    .Q(\state_machinemult0.counter [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \state_machinemult0.state_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(init_LUT4_A_Z[3]),
    .LSR(1'h0),
    .Q(\state_machinemult0.state [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \state_machinemult0.state_TRELLIS_FF_Q_1  (
    .CLK(clk),
    .DI(\state_machinemult0.state_TRELLIS_FF_Q_1_DI ),
    .LSR(1'h0),
    .Q(\state_machinemult0.state [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \state_machinemult0.state_TRELLIS_FF_Q_1_DI_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(rst),
    .D(\regA0.shift ),
    .Z(\state_machinemult0.state_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/felipe-zorro/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \state_machinemult0.state_TRELLIS_FF_Q_2  (
    .CLK(clk),
    .DI(init_LUT4_A_Z[0]),
    .LSR(1'h0),
    .Q(\state_machinemult0.state [0])
  );
  assign init_LUT4_C_Z_PFUMX_Z_1_C0[3:0] = { \regB0.Bout [4], \regB0.Bout [5], \regB0.Bout [6], \regB0.Bout [7] };
  assign init_LUT4_C_Z[2:1] = { \state_machinemult0.state [1], rst };
  assign { init_LUT4_A_D_LUT4_Z_C[4], init_LUT4_A_D_LUT4_Z_C[2:0] } = { init_LUT4_C_Z[0], \state_machinemult0.state [1], rst, init_LUT4_C_Z[4] };
  assign init_LUT4_A_D[2:0] = { \state_machinemult0.state [0], rst, init };
  assign \regA0.shift_LUT4_D_Z_PFUMX_BLUT_Z [1:0] = { \regA0.Aout [14], A[15] };
  assign init_LUT4_C_Z_PFUMX_Z_C0[3:0] = { \state_machinemult0.b0 , \regB0.Bout [1], \regB0.Bout [2], \regB0.Bout [3] };
  assign init_LUT4_A_Z[2:1] = { \acc0.acc_TRELLIS_FF_Q_DI , \state_machinemult0.state_TRELLIS_FF_Q_1_DI  };
  assign init_LUT4_A_1_Z[0] = done;
  assign R = \acc0.R ;
  assign \acc0.A  = \regA0.Aout ;
  assign \acc0.clk  = clk;
  assign \comp0.B  = { \regB0.Bout [15:1], \state_machinemult0.b0  };
  assign \regA0.A  = A;
  assign \regA0.clk  = clk;
  assign \regB0.B  = B;
  assign \regB0.Bout [0] = \state_machinemult0.b0 ;
  assign \regB0.clk  = clk;
  assign \regB0.shift  = \regA0.shift ;
  assign \state_machinemult0.acc  = \acc0.acc ;
  assign \state_machinemult0.clk  = clk;
  assign \state_machinemult0.done  = done;
  assign \state_machinemult0.init  = init;
  assign \state_machinemult0.rst  = rst;
  assign \state_machinemult0.sh  = \regA0.shift ;
  assign { \state_machinemult0.state [5:4], \state_machinemult0.state [2] } = { \regA0.shift , done, \acc0.acc  };
  assign w_a = \regA0.Aout ;
  assign w_acc = \acc0.acc ;
  assign w_b = { \regB0.Bout [15:1], \state_machinemult0.b0  };
  assign w_sh = \regA0.shift ;
endmodule
