/* Generated by Yosys 0.57+263 (git sha1 da2e021e3, g++ 14.2.0-19ubuntu2 -fPIC -O3) */

/* hdlname = "mult_32" */
/* top =  1  */
/* src = "mult_32.v:1.1-27.10" */
module mult_32(clk, rst, init, A, B, pp, done);
  /* src = "mult_32.v:4.9-4.12" */
  input clk;
  wire clk;
  /* src = "mult_32.v:3.9-3.12" */
  input rst;
  wire rst;
  /* src = "mult_32.v:5.9-5.13" */
  input init;
  wire init;
  /* src = "mult_32.v:6.16-6.17" */
  input [15:0] A;
  wire [15:0] A;
  /* src = "mult_32.v:7.16-7.17" */
  input [15:0] B;
  wire [15:0] B;
  /* src = "mult_32.v:8.17-8.19" */
  output [31:0] pp;
  wire [31:0] pp;
  /* src = "mult_32.v:9.10-9.14" */
  output done;
  wire done;
  /* hdlname = "acc0 A" */
  /* src = "acc.v:3.16-3.17" */
  wire [31:0] \acc0.A ;
  /* hdlname = "acc0 add" */
  /* src = "acc.v:4.9-4.12" */
  wire \acc0.add ;
  /* hdlname = "acc0 clk" */
  /* src = "acc.v:2.9-2.12" */
  wire \acc0.clk ;
  /* hdlname = "acc0 pp" */
  /* src = "acc.v:6.21-6.23" */
  wire [31:0] \acc0.pp ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_10_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_11_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_12_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_13_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_14_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_15_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_1_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_2_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  /* unused_bits = "0" */
  wire \acc0.pp_CCU2C_A0_3_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_4_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_5_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_6_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_7_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_8_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_9_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4|/usr/local/bin/../share/yosys/ecp5/cells_sim.v:82.9-82.13" */
  wire \acc0.pp_CCU2C_A0_COUT ;
  /* force_downto = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:34.26-34.27" */
  wire [31:0] \acc0.pp_TRELLIS_FF_Q_DI ;
  /* hdlname = "acc0 rst" */
  /* src = "acc.v:5.9-5.12" */
  wire \acc0.rst ;
  /* hdlname = "comp0 B" */
  /* src = "comp.v:2.15-2.16" */
  wire [15:0] \comp0.B ;
  /* hdlname = "control0 add" */
  /* src = "control_mult.v:13.13-13.16" */
  wire \control0.add ;
  wire \control0.add_TRELLIS_FF_Q_DI ;
  /* hdlname = "control0 clk" */
  /* src = "control_mult.v:4.8-4.11" */
  wire \control0.clk ;
  /* hdlname = "control0 count" */
  /* src = "control_mult.v:32.11-32.16" */
  wire [3:0] \control0.count ;
  /* force_downto = 32'd1 */
  /* src = "control_mult.v:84.17-84.26|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" */
  wire [3:0] \control0.count_TRELLIS_FF_Q_3_DI ;
  /* force_downto = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [1:0] \control0.count_TRELLIS_FF_Q_CE ;
  /* force_downto = 32'd1 */
  /* src = "control_mult.v:84.17-84.26|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" */
  wire [3:0] \control0.count_TRELLIS_FF_Q_DI ;
  wire \control0.count_TRELLIS_FF_Q_LSR ;
  /* hdlname = "control0 done" */
  /* src = "control_mult.v:10.13-10.17" */
  wire \control0.done ;
  /* force_downto = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [4:0] \control0.done_TRELLIS_FF_Q_DI ;
  /* hdlname = "control0 init" */
  /* src = "control_mult.v:7.8-7.12" */
  wire \control0.init ;
  /* hdlname = "control0 lsb_B" */
  /* src = "control_mult.v:6.8-6.13" */
  wire \control0.lsb_B ;
  /* force_downto = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [5:0] \control0.lsb_B_LUT4_D_Z ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \control0.lsb_B_LUT4_D_Z_PFUMX_Z_ALUT ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \control0.lsb_B_LUT4_D_Z_PFUMX_Z_BLUT ;
  /* force_downto = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:108.23-108.24" */
  wire [5:0] \control0.lsb_B_PFUMX_C0_Z ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:141.34-141.36" */
  wire \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D0 ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:141.22-141.24" */
  wire \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D0_PFUMX_Z_ALUT ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:141.18-141.20" */
  wire \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D0_PFUMX_Z_BLUT ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:141.38-141.40" */
  wire \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D1 ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:141.30-141.32" */
  wire \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D1_PFUMX_Z_ALUT ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:141.26-141.28" */
  wire \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D1_PFUMX_Z_BLUT ;
  /* force_downto = 32'd1 */
  /* src = "control_mult.v:78.9-78.9|control_mult.v:38.5-89.11|/usr/local/bin/../share/yosys/techmap.v:583.21-583.22" */
  wire [2:0] \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:141.34-141.36" */
  wire \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D0 ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:141.22-141.24" */
  wire \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D0_PFUMX_Z_ALUT ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:141.18-141.20" */
  wire \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D0_PFUMX_Z_BLUT ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:141.38-141.40" */
  wire \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D1 ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:141.30-141.32" */
  wire \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D1_PFUMX_Z_ALUT ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:141.26-141.28" */
  wire \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D1_PFUMX_Z_BLUT ;
  /* hdlname = "control0 reset" */
  /* src = "control_mult.v:12.13-12.18" */
  wire \control0.reset ;
  wire \control0.reset_TRELLIS_FF_Q_DI ;
  /* hdlname = "control0 rst" */
  /* src = "control_mult.v:5.8-5.11" */
  wire \control0.rst ;
  /* hdlname = "control0 sh" */
  /* src = "control_mult.v:11.13-11.15" */
  wire \control0.sh ;
  wire \control0.sh_LUT4_D_Z ;
  wire \control0.sh_TRELLIS_FF_Q_CE ;
  wire \control0.sh_TRELLIS_FF_Q_DI ;
  /* hdlname = "control0 state" */
  /* src = "control_mult.v:22.12-22.17" */
  wire [2:0] \control0.state ;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire init_LUT4_A_1_Z;
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire init_LUT4_A_Z;
  /* hdlname = "lsr0 clk" */
  /* src = "lsr.v:2.9-2.12" */
  wire \lsr0.clk ;
  /* hdlname = "lsr0 in_A" */
  /* src = "lsr.v:3.15-3.19" */
  wire [15:0] \lsr0.in_A ;
  /* hdlname = "lsr0 load" */
  /* src = "lsr.v:4.9-4.13" */
  wire \lsr0.load ;
  /* hdlname = "lsr0 s_A" */
  /* src = "lsr.v:6.20-6.23" */
  wire [31:0] \lsr0.s_A ;
  wire [15:1] \lsr0.s_A_TRELLIS_FF_Q_31_DI ;
  /* hdlname = "lsr0 shift" */
  /* src = "lsr.v:5.9-5.14" */
  wire \lsr0.shift ;
  /* hdlname = "rsr0 clk" */
  /* src = "rsr.v:2.9-2.12" */
  wire \rsr0.clk ;
  /* hdlname = "rsr0 in_B" */
  /* src = "rsr.v:3.15-3.19" */
  wire [15:0] \rsr0.in_B ;
  /* hdlname = "rsr0 load" */
  /* src = "rsr.v:4.9-4.13" */
  wire \rsr0.load ;
  /* hdlname = "rsr0 s_B" */
  /* src = "rsr.v:6.20-6.23" */
  wire [15:0] \rsr0.s_B ;
  wire [14:0] \rsr0.s_B_TRELLIS_FF_Q_9_DI ;
  wire \rsr0.s_B_TRELLIS_FF_Q_LSR ;
  /* hdlname = "rsr0 shift" */
  /* src = "rsr.v:5.9-5.14" */
  wire \rsr0.shift ;
  /* src = "mult_32.v:16.15-16.18" */
  wire [31:0] w_A;
  /* src = "mult_32.v:17.15-17.18" */
  wire [15:0] w_B;
  /* src = "mult_32.v:13.8-13.13" */
  wire w_add;
  /* src = "mult_32.v:12.8-12.15" */
  wire w_reset;
  /* src = "mult_32.v:11.8-11.12" */
  wire w_sh;
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) A_LUT4_B (
    .A(1'h0),
    .B(A[1]),
    .C(\control0.reset ),
    .D(\lsr0.s_A [0]),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_1 (
    .A(1'h0),
    .B(A[2]),
    .C(\lsr0.s_A [1]),
    .D(\control0.reset ),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_10 (
    .A(1'h0),
    .B(A[11]),
    .C(\lsr0.s_A [10]),
    .D(\control0.reset ),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_11 (
    .A(1'h0),
    .B(A[12]),
    .C(\lsr0.s_A [11]),
    .D(\control0.reset ),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_12 (
    .A(1'h0),
    .B(A[13]),
    .C(\lsr0.s_A [12]),
    .D(\control0.reset ),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_13 (
    .A(1'h0),
    .B(A[14]),
    .C(\lsr0.s_A [13]),
    .D(\control0.reset ),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_14 (
    .A(1'h0),
    .B(A[15]),
    .C(\lsr0.s_A [14]),
    .D(\control0.reset ),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_2 (
    .A(1'h0),
    .B(A[3]),
    .C(\lsr0.s_A [2]),
    .D(\control0.reset ),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_3 (
    .A(1'h0),
    .B(A[4]),
    .C(\lsr0.s_A [3]),
    .D(\control0.reset ),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_4 (
    .A(1'h0),
    .B(A[5]),
    .C(\lsr0.s_A [4]),
    .D(\control0.reset ),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_5 (
    .A(1'h0),
    .B(A[6]),
    .C(\lsr0.s_A [5]),
    .D(\control0.reset ),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_6 (
    .A(1'h0),
    .B(A[7]),
    .C(\lsr0.s_A [6]),
    .D(\control0.reset ),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_7 (
    .A(1'h0),
    .B(A[8]),
    .C(\lsr0.s_A [7]),
    .D(\control0.reset ),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_8 (
    .A(1'h0),
    .B(A[9]),
    .C(\lsr0.s_A [8]),
    .D(\control0.reset ),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_9 (
    .A(1'h0),
    .B(A[10]),
    .C(\lsr0.s_A [9]),
    .D(\control0.reset ),
    .Z(\lsr0.s_A_TRELLIS_FF_Q_31_DI [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B (
    .A(1'h0),
    .B(B[0]),
    .C(\rsr0.s_B [1]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_1 (
    .A(1'h0),
    .B(B[1]),
    .C(\rsr0.s_B [2]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_10 (
    .A(1'h0),
    .B(B[10]),
    .C(\rsr0.s_B [11]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_11 (
    .A(1'h0),
    .B(B[11]),
    .C(\rsr0.s_B [12]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_12 (
    .A(1'h0),
    .B(B[12]),
    .C(\rsr0.s_B [13]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_13 (
    .A(1'h0),
    .B(B[13]),
    .C(\rsr0.s_B [14]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_14 (
    .A(1'h0),
    .B(B[14]),
    .C(\rsr0.s_B [15]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_2 (
    .A(1'h0),
    .B(B[2]),
    .C(\rsr0.s_B [3]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_3 (
    .A(1'h0),
    .B(B[3]),
    .C(\rsr0.s_B [4]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_4 (
    .A(1'h0),
    .B(B[4]),
    .C(\rsr0.s_B [5]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_5 (
    .A(1'h0),
    .B(B[5]),
    .C(\rsr0.s_B [6]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_6 (
    .A(1'h0),
    .B(B[6]),
    .C(\rsr0.s_B [7]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_7 (
    .A(1'h0),
    .B(B[7]),
    .C(\rsr0.s_B [8]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_8 (
    .A(1'h0),
    .B(B[8]),
    .C(\rsr0.s_B [9]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_9 (
    .A(1'h0),
    .B(B[9]),
    .C(\rsr0.s_B [10]),
    .D(\control0.reset ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_DI [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0  (
    .A0(\acc0.pp [8]),
    .A1(\acc0.pp [9]),
    .B0(\lsr0.s_A [8]),
    .B1(\lsr0.s_A [9]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_1_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [8]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_1  (
    .A0(\acc0.pp [6]),
    .A1(\acc0.pp [7]),
    .B0(\lsr0.s_A [6]),
    .B1(\lsr0.s_A [7]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_2_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [6]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_10  (
    .A0(\acc0.pp [18]),
    .A1(\acc0.pp [19]),
    .B0(\lsr0.s_A [18]),
    .B1(\lsr0.s_A [19]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_11_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_10_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [18]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_11  (
    .A0(\acc0.pp [16]),
    .A1(\acc0.pp [17]),
    .B0(\lsr0.s_A [16]),
    .B1(\lsr0.s_A [17]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_12_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_11_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [16]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_12  (
    .A0(\acc0.pp [14]),
    .A1(\acc0.pp [15]),
    .B0(\lsr0.s_A [14]),
    .B1(\lsr0.s_A [15]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_13_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_12_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [14]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_13  (
    .A0(\acc0.pp [12]),
    .A1(\acc0.pp [13]),
    .B0(\lsr0.s_A [12]),
    .B1(\lsr0.s_A [13]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_14_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_13_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [12]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_14  (
    .A0(\acc0.pp [10]),
    .A1(\acc0.pp [11]),
    .B0(\lsr0.s_A [10]),
    .B1(\lsr0.s_A [11]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_14_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [10]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_15  (
    .A0(\acc0.pp [0]),
    .A1(\acc0.pp [1]),
    .B0(\lsr0.s_A [0]),
    .B1(\lsr0.s_A [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\acc0.pp_CCU2C_A0_15_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [0]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_2  (
    .A0(\acc0.pp [4]),
    .A1(\acc0.pp [5]),
    .B0(\lsr0.s_A [4]),
    .B1(\lsr0.s_A [5]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_4_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_2_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [4]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_3  (
    .A0(\acc0.pp [30]),
    .A1(\acc0.pp [31]),
    .B0(\lsr0.s_A [30]),
    .B1(\lsr0.s_A [31]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_5_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_3_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [30]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_4  (
    .A0(\acc0.pp [2]),
    .A1(\acc0.pp [3]),
    .B0(\lsr0.s_A [2]),
    .B1(\lsr0.s_A [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_15_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_4_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [2]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_5  (
    .A0(\acc0.pp [28]),
    .A1(\acc0.pp [29]),
    .B0(\lsr0.s_A [28]),
    .B1(\lsr0.s_A [29]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_6_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_5_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [28]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_6  (
    .A0(\acc0.pp [26]),
    .A1(\acc0.pp [27]),
    .B0(\lsr0.s_A [26]),
    .B1(\lsr0.s_A [27]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_7_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_6_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [26]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_7  (
    .A0(\acc0.pp [24]),
    .A1(\acc0.pp [25]),
    .B0(\lsr0.s_A [24]),
    .B1(\lsr0.s_A [25]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_8_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_7_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [24]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_8  (
    .A0(\acc0.pp [22]),
    .A1(\acc0.pp [23]),
    .B0(\lsr0.s_A [22]),
    .B1(\lsr0.s_A [23]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_9_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_8_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [22]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:15.21-15.27|/usr/local/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.pp_CCU2C_A0_9  (
    .A0(\acc0.pp [20]),
    .A1(\acc0.pp [21]),
    .B0(\lsr0.s_A [20]),
    .B1(\lsr0.s_A [21]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.pp_CCU2C_A0_10_COUT ),
    .COUT(\acc0.pp_CCU2C_A0_9_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.pp_TRELLIS_FF_Q_DI [20]),
    .S1(\acc0.pp_TRELLIS_FF_Q_DI [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [31]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_1  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [30]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [30])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_10  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [21]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_11  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [20]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_12  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [19]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_13  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [18]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_14  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [17]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_15  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [16]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_16  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [15]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_17  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [14]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_18  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [13]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_19  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [12]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_2  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [29]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_20  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [11]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_21  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [10]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_22  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [9]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_23  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [8]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_24  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [7]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_25  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [6]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_26  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [5]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_27  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [4]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_28  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [3]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_29  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [2]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_3  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [28]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [28])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_30  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [1]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_31  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [0]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_4  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [27]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_5  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [26]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [26])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_6  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [25]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_7  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [24]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [24])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_8  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [23]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc.v:10.1-17.9|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.pp_TRELLIS_FF_Q_9  (
    .CE(\control0.add ),
    .CLK(clk),
    .DI(\acc0.pp_TRELLIS_FF_Q_DI [22]),
    .LSR(\control0.reset ),
    .Q(\acc0.pp [22])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:34.1-91.4|/usr/local/bin/../share/yosys/ecp5/cells_map.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \control0.add_TRELLIS_FF_Q  (
    .CE(\control0.sh_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\control0.add_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\control0.add )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfcc0)
  ) \control0.add_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.add_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:34.1-91.4|/usr/local/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.count_TRELLIS_FF_Q  (
    .CE(\control0.count_TRELLIS_FF_Q_CE [1]),
    .CLK(clk),
    .DI(\control0.count_TRELLIS_FF_Q_DI [3]),
    .LSR(\control0.count_TRELLIS_FF_Q_LSR ),
    .Q(\control0.count [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:34.1-91.4|/usr/local/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.count_TRELLIS_FF_Q_1  (
    .CE(\control0.count_TRELLIS_FF_Q_CE [1]),
    .CLK(clk),
    .DI(\control0.count_TRELLIS_FF_Q_DI [2]),
    .LSR(\control0.count_TRELLIS_FF_Q_LSR ),
    .Q(\control0.count [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:34.1-91.4|/usr/local/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.count_TRELLIS_FF_Q_2  (
    .CE(\control0.count_TRELLIS_FF_Q_CE [1]),
    .CLK(clk),
    .DI(\control0.count_TRELLIS_FF_Q_DI [1]),
    .LSR(\control0.count_TRELLIS_FF_Q_LSR ),
    .Q(\control0.count [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:34.1-91.4|/usr/local/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.count_TRELLIS_FF_Q_3  (
    .CE(\control0.count_TRELLIS_FF_Q_CE [1]),
    .CLK(clk),
    .DI(\control0.count_TRELLIS_FF_Q_3_DI [0]),
    .LSR(\control0.count_TRELLIS_FF_Q_LSR ),
    .Q(\control0.count [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \control0.count_TRELLIS_FF_Q_3_DI_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\control0.count [0]),
    .Z(\control0.count_TRELLIS_FF_Q_3_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h6aaa)
  ) \control0.count_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(\control0.count [3]),
    .B(\control0.count [2]),
    .C(\control0.count [1]),
    .D(\control0.count [0]),
    .Z(\control0.count_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3ccc)
  ) \control0.count_TRELLIS_FF_Q_DI_LUT4_Z_1  (
    .A(1'h0),
    .B(\control0.count [2]),
    .C(\control0.count [1]),
    .D(\control0.count [0]),
    .Z(\control0.count_TRELLIS_FF_Q_DI [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0ff0)
  ) \control0.count_TRELLIS_FF_Q_DI_LUT4_Z_2  (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.count [1]),
    .D(\control0.count [0]),
    .Z(\control0.count_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \control0.count_TRELLIS_FF_Q_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.state [2]),
    .D(\control0.count_TRELLIS_FF_Q_CE [1]),
    .Z(\control0.count_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:34.1-91.4|/usr/local/bin/../share/yosys/ecp5/cells_map.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \control0.done_TRELLIS_FF_Q  (
    .CE(\control0.sh_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\control0.done_TRELLIS_FF_Q_DI [4]),
    .LSR(1'h0),
    .Q(\control0.done )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h000c)
  ) \control0.done_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.done_TRELLIS_FF_Q_DI [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.lsb_B_LUT4_D  (
    .A(\rsr0.s_B [3]),
    .B(\rsr0.s_B [2]),
    .C(\rsr0.s_B [1]),
    .D(\control0.lsb_B ),
    .Z(\control0.lsb_B_LUT4_D_Z [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h0030)
  ) \control0.lsb_B_LUT4_D_Z_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.lsb_B_LUT4_D_Z [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.lsb_B_LUT4_D_Z_LUT4_Z_1  (
    .A(\rsr0.s_B [11]),
    .B(\rsr0.s_B [10]),
    .C(\rsr0.s_B [9]),
    .D(\rsr0.s_B [8]),
    .Z(\control0.lsb_B_LUT4_D_Z [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.lsb_B_LUT4_D_Z_LUT4_Z_2  (
    .A(\rsr0.s_B [15]),
    .B(\rsr0.s_B [14]),
    .C(\rsr0.s_B [13]),
    .D(\rsr0.s_B [12]),
    .Z(\control0.lsb_B_LUT4_D_Z [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.lsb_B_LUT4_D_Z_LUT4_Z_3  (
    .A(\rsr0.s_B [7]),
    .B(\rsr0.s_B [6]),
    .C(\rsr0.s_B [5]),
    .D(\rsr0.s_B [4]),
    .Z(\control0.lsb_B_LUT4_D_Z [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \control0.lsb_B_LUT4_D_Z_PFUMX_Z  (
    .ALUT(\control0.lsb_B_LUT4_D_Z_PFUMX_Z_ALUT ),
    .BLUT(\control0.lsb_B_LUT4_D_Z_PFUMX_Z_BLUT ),
    .C0(\control0.done_TRELLIS_FF_Q_DI [4]),
    .Z(\control0.lsb_B_LUT4_D_Z [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hd557)
  ) \control0.lsb_B_LUT4_D_Z_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\control0.count [3]),
    .B(\control0.count [2]),
    .C(\control0.count [1]),
    .D(\control0.count [0]),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control0.lsb_B_LUT4_D_Z_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.lsb_B_LUT4_D_Z_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \control0.lsb_B_PFUMX_C0  (
    .ALUT(init_LUT4_A_Z),
    .BLUT(init_LUT4_A_1_Z),
    .C0(\control0.lsb_B ),
    .Z(\control0.lsb_B_PFUMX_C0_Z [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:154.21-154.62" */
  L6MUX21 \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD  (
    .D0(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D0 ),
    .D1(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D1 ),
    .SD(\control0.lsb_B_PFUMX_C0_Z [5]),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:152.19-152.65" */
  PFUMX \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D0_PFUMX_Z  (
    .ALUT(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D0_PFUMX_Z_ALUT ),
    .BLUT(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D0_PFUMX_Z_BLUT ),
    .C0(\control0.lsb_B_LUT4_D_Z [4]),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:144.39-145.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:142.39-143.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:153.19-153.65" */
  PFUMX \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D1_PFUMX_Z  (
    .ALUT(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D1_PFUMX_Z_ALUT ),
    .BLUT(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D1_PFUMX_Z_BLUT ),
    .C0(\control0.lsb_B_LUT4_D_Z [4]),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:149.39-150.56" */
  LUT4 #(
    .INIT(16'h7fff)
  ) \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\control0.lsb_B_LUT4_D_Z [0]),
    .B(\control0.lsb_B_LUT4_D_Z [1]),
    .C(\control0.lsb_B_LUT4_D_Z [2]),
    .D(\control0.lsb_B_LUT4_D_Z [3]),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:147.39-148.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:154.21-154.62" */
  L6MUX21 \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z  (
    .D0(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D0 ),
    .D1(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D1 ),
    .SD(\control0.lsb_B_LUT4_D_Z [5]),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:152.19-152.65" */
  PFUMX \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D0_PFUMX_Z  (
    .ALUT(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D0_PFUMX_Z_ALUT ),
    .BLUT(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D0_PFUMX_Z_BLUT ),
    .C0(\control0.lsb_B_LUT4_D_Z [4]),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:144.39-145.56" */
  LUT4 #(
    .INIT(16'h8000)
  ) \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\control0.lsb_B_LUT4_D_Z [0]),
    .B(\control0.lsb_B_LUT4_D_Z [1]),
    .C(\control0.lsb_B_LUT4_D_Z [2]),
    .D(\control0.lsb_B_LUT4_D_Z [3]),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:142.39-143.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:153.19-153.65" */
  PFUMX \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D1_PFUMX_Z  (
    .ALUT(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D1_PFUMX_Z_ALUT ),
    .BLUT(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D1_PFUMX_Z_BLUT ),
    .C0(\control0.lsb_B_LUT4_D_Z [4]),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:149.39-150.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:147.39-148.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_L6MUX21_Z_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.state [2]),
    .D(\control0.state [0]),
    .Z(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \control0.lsb_B_TRELLIS_FF_Q  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [0]),
    .LSR(1'h0),
    .Q(\control0.lsb_B )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:34.1-91.4|/usr/local/bin/../share/yosys/ecp5/cells_map.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \control0.reset_TRELLIS_FF_Q  (
    .CE(\control0.sh_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\control0.reset_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccc3)
  ) \control0.reset_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.reset_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) \control0.sh_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.reset ),
    .D(\control0.sh ),
    .Z(\control0.sh_LUT4_D_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:34.1-91.4|/usr/local/bin/../share/yosys/ecp5/cells_map.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \control0.sh_TRELLIS_FF_Q  (
    .CE(\control0.sh_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\control0.sh_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\control0.sh )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) \control0.sh_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.sh_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:34.1-91.4|/usr/local/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z [2]),
    .LSR(rst),
    .Q(\control0.state [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:34.1-91.4|/usr/local/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q_1  (
    .CLK(clk),
    .DI(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z [1]),
    .LSR(rst),
    .Q(\control0.state [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:34.1-91.4|/usr/local/bin/../share/yosys/ecp5/cells_map.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q_2  (
    .CLK(clk),
    .DI(\control0.lsb_B_PFUMX_C0_Z_L6MUX21_SD_Z [0]),
    .LSR(rst),
    .Q(\control0.state [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hfcfd)
  ) init_LUT4_A (
    .A(init),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(init_LUT4_A_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hfffd)
  ) init_LUT4_A_1 (
    .A(init),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(init_LUT4_A_1_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [30]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_1  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [29]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [30])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_10  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [20]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_11  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [19]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_12  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [18]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_13  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [17]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_14  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [16]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_15  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [15]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_16  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(A[0]),
    .LSR(\rsr0.s_B_TRELLIS_FF_Q_LSR ),
    .Q(\lsr0.s_A [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_17  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [15]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_18  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [14]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_19  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [13]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_2  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [28]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_20  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [12]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_21  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [11]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_22  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [10]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_23  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [9]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_24  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [8]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_25  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [7]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_26  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [6]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_27  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [5]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_28  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [4]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_29  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [3]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_3  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [27]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [28])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_30  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [2]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr0.s_A_TRELLIS_FF_Q_31  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\lsr0.s_A_TRELLIS_FF_Q_31_DI [1]),
    .LSR(1'h0),
    .Q(\lsr0.s_A [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_4  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [26]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_5  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [25]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [26])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_6  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [24]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_7  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [23]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [24])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_8  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [22]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr0.s_A_TRELLIS_FF_Q_9  (
    .CE(\control0.sh ),
    .CLK(clk),
    .DI(\lsr0.s_A [21]),
    .LSR(\control0.reset ),
    .Q(\lsr0.s_A [22])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rsr0.s_B_TRELLIS_FF_Q  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(B[15]),
    .LSR(\rsr0.s_B_TRELLIS_FF_Q_LSR ),
    .Q(\rsr0.s_B [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_1  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [14]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_10  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [5]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_11  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [4]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_12  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [3]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_13  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [2]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_14  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [1]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_2  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [13]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_3  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [12]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_4  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [11]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_5  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [10]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_6  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [9]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_7  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [8]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_8  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [7]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:8.1-15.7|/usr/local/bin/../share/yosys/ecp5/cells_map.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_9  (
    .CE(\control0.sh_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rsr0.s_B_TRELLIS_FF_Q_9_DI [6]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \rsr0.s_B_TRELLIS_FF_Q_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.reset ),
    .D(\control0.sh ),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hff03)
  ) rst_LUT4_B (
    .A(1'h0),
    .B(rst),
    .C(\control0.state [2]),
    .D(\control0.count_TRELLIS_FF_Q_CE [1]),
    .Z(\control0.sh_TRELLIS_FF_Q_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/usr/local/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h0003)
  ) rst_LUT4_B_1 (
    .A(1'h0),
    .B(rst),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.count_TRELLIS_FF_Q_CE [1])
  );
  assign \control0.done_TRELLIS_FF_Q_DI [3:0] = { \control0.count [0], \control0.count [1], \control0.count [2], \control0.count [3] };
  assign \control0.count_TRELLIS_FF_Q_CE [0] = \control0.state [2];
  assign \control0.lsb_B_PFUMX_C0_Z [4:0] = \control0.lsb_B_LUT4_D_Z [4:0];
  assign \control0.count_TRELLIS_FF_Q_3_DI [3:1] = \control0.count [3:1];
  assign \control0.count_TRELLIS_FF_Q_DI [0] = \control0.count_TRELLIS_FF_Q_3_DI [0];
  assign \acc0.A  = \lsr0.s_A ;
  assign \acc0.add  = \control0.add ;
  assign \acc0.clk  = clk;
  assign \acc0.rst  = \control0.reset ;
  assign \comp0.B  = { \rsr0.s_B [15:1], \control0.lsb_B  };
  assign \control0.clk  = clk;
  assign \control0.init  = init;
  assign \control0.rst  = rst;
  assign done = \control0.done ;
  assign \lsr0.clk  = clk;
  assign \lsr0.in_A  = A;
  assign \lsr0.load  = \control0.reset ;
  assign \lsr0.shift  = \control0.sh ;
  assign pp = \acc0.pp ;
  assign \rsr0.clk  = clk;
  assign \rsr0.in_B  = B;
  assign \rsr0.load  = \control0.reset ;
  assign \rsr0.s_B [0] = \control0.lsb_B ;
  assign \rsr0.shift  = \control0.sh ;
  assign w_A = \lsr0.s_A ;
  assign w_B = { \rsr0.s_B [15:1], \control0.lsb_B  };
  assign w_add = \control0.add ;
  assign w_reset = \control0.reset ;
  assign w_sh = \control0.sh ;
endmodule
